---
title: "Take Home Ex3: VAST Challenge 2024 Mini-Challenge 3"
author: "Kristine Joy Paas"
date: "22 May 2024"
date-modified: "last-modified"
format: html
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true
---

# Setup

## Loading Packages

```{r}
#| label: setup
pacman::p_load(jsonlite, tidyverse, ggraph, tidygraph, visNetwork, patchwork, ggtext, knitr)
```

```{r}
#| echo: false
font_family = "Roboto Condensed"
```

## Loading Data

```{r}
mc3_data <- fromJSON("data/mc3.json")
```

# Data Wrangling

## Extracting Nodes

```{r}
mc3_nodes <- as_tibble(mc3_data$nodes) %>%
  mutate(
    id = as.character(id),
    subtype = strsplit(type, ".", fixed=TRUE) %>% sapply(tail, n=1),
    type = strsplit(type, ".", fixed=TRUE) %>% sapply('[', 2)
  ) %>%
  select(id, type, subtype)

mc3_nodes %>% head(n = 10) %>% kable()
```

## Extracting Edges

```{r}
mc3_edges <- as_tibble(mc3_data$links) %>%
  mutate(
    source = as.character(source),
    target = as.character(target),
    subtype = strsplit(type, ".", fixed = TRUE) %>% sapply(tail, n = 1),
    type = ifelse(
      grepl("Event.Owns", type),
      "Ownership",
      ifelse(grepl("Relationship", type), "Relationship", "Employment")
    )
  ) %>%
  select(source, target, type, subtype) %>%
  distinct() %>%
  filter(source != target)

mc3_edges %>% head(n = 10) %>% kable()
```

# Questions

## Q4: Relations with SouthSeafood Express Corp

### Direct Relations

#### Edges

```{r}
ssfec_edges <- mc3_edges %>%
  filter(source == "SouthSeafood Express Corp" |
           target == "SouthSeafood Express Corp")
ssfec_edges %>% kable()
```

#### Nodes

```{r}
ssfec_nodes <- mc3_nodes %>%
  filter(id %in% ssfec_edges$source |
           id %in% ssfec_edges$target) %>%
  mutate(
    focus = (id == "SouthSeafood Express Corp")
  )
ssfec_nodes %>% kable()
```

#### Graph

```{r}
ssfec_graph <- tbl_graph(nodes = ssfec_nodes, edges = ssfec_edges, directed = TRUE)
```

```{r}
ggraph(ssfec_graph, layout = "linear", circular = TRUE) +
  
  # Render nodes
  geom_node_point(aes(color = focus), show.legend = FALSE, size = 30) +
  geom_node_text(
    aes(label = str_wrap(id, width = -1)),
    family = font_family,
    size = 3,
    color = "white"
  ) +
  scale_color_manual(values = c("blue", "gold3")) +
  
  # Render edges
  geom_edge_link(
    aes(label = subtype),
    # Control arrow
    arrow = arrow(type = "closed", length = unit(0.025, "npc")),
    end_cap = circle(12, "mm"),
    start_cap = circle(12, "mm"),
    # Format labels
    angle_calc = "along",
    label_dodge = unit(0.04, "npc"),
    family = font_family,
    show.legend = FALSE
  ) +
  
  # Hack to reduce distance between nodes
  # This is to not clip the nodes in the edge of the plot
  # ref: https://stackoverflow.com/a/66991383
  ylim(-1.3, 0.8) +
  xlim(-1, 1) +
  
  # Style graph
  unset_graph_style() +
  theme_graph(base_family = font_family, plot_margin = margin(0)) +
  plot_annotation(title = "SouthSeafood Express Corp's Direct Network", subtitle = "Two other fishing companies, <span style='color:blue;'>**AguaLeska Transit N.V.**</span> and <span style='color:blue;'>**Tainamarine Fishing Co**</span> hold shares in<br />SouthSeafood Express Corp.") &
  theme(
    text = element_text(family = font_family),
    plot.title = element_text(face = "bold", size = rel(1.4)),
    plot.subtitle = element_markdown(color = "grey50")
  )
```

# References

<https://blogs.cornell.edu/info2040/2015/10/19/three-degrees-of-influence-how-far-can-you-reach-people/>
