{
  "hash": "90619aa91c00f26850c9aa83d33e8850",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Ex3: VAST Challenge 2024 Mini-Challenge 3 [WIP]\"\nauthor: \"Kristine Joy Paas\"\ndate: \"22 May 2024\"\ndate-modified: \"last-modified\"\nformat: html\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n\n# 1 Overview\n\n# 2 Setup\n\n## 2.1 Loading Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  jsonlite,\n  tidyverse,\n  ggraph,\n  tidygraph,\n  visNetwork,\n  patchwork,\n  ggtext,\n  knitr,\n  igraph,\n  ggiraph\n)\n```\n:::\n\n\nWe will also set some values to have consistency throughout all graphs. This is also so that we don't have to search and replace all instances of these\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFONT_FAMILY = \"Roboto Condensed\"\n```\n:::\n\n\n## 2.2 Loading Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_data <- fromJSON(\"data/mc3.json\")\nglimpse(mc3_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi TRUE\n $ graph     : Named list()\n $ nodes     :'data.frame':\t60520 obs. of  15 variables:\n  ..$ type             : chr [1:60520] \"Entity.Organization.Company\" \"Entity.Organization.Company\" \"Entity.Organization.Company\" \"Entity.Organization.Company\" ...\n  ..$ country          : chr [1:60520] \"Uziland\" \"Mawalara\" \"Uzifrica\" \"Islavaragon\" ...\n  ..$ ProductServices  : chr [1:60520] \"Unknown\" \"Furniture and home accessories\" \"Food products\" \"Unknown\" ...\n  ..$ PointOfContact   : chr [1:60520] \"Rebecca Lewis\" \"Michael Lopez\" \"Steven Robertson\" \"Anthony Wyatt\" ...\n  ..$ HeadOfOrg        : chr [1:60520] \"Émilie-Susan Benoit\" \"Honoré Lemoine\" \"Jules Labbé\" \"Dr. Víctor Hurtado\" ...\n  ..$ founding_date    : chr [1:60520] \"1954-04-24T00:00:00\" \"2009-06-12T00:00:00\" \"2029-12-15T00:00:00\" \"1972-02-16T00:00:00\" ...\n  ..$ revenue          : num [1:60520] 5995 71767 0 0 4747 ...\n  ..$ TradeDescription : chr [1:60520] \"Unknown\" \"Abbott-Gomez is a leading manufacturer and supplier of high-quality furniture and home accessories, catering to\"| __truncated__ \"Abbott-Harrison is a leading manufacturer of high-quality food products, including baked goods, snacks, and bev\"| __truncated__ \"Unknown\" ...\n  ..$ _last_edited_by  : chr [1:60520] \"Pelagia Alethea Mordoch\" \"Pelagia Alethea Mordoch\" \"Pelagia Alethea Mordoch\" \"Pelagia Alethea Mordoch\" ...\n  ..$ _last_edited_date: chr [1:60520] \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" ...\n  ..$ _date_added      : chr [1:60520] \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" ...\n  ..$ _raw_source      : chr [1:60520] \"Existing Corporate Structure Data\" \"Existing Corporate Structure Data\" \"Existing Corporate Structure Data\" \"Existing Corporate Structure Data\" ...\n  ..$ _algorithm       : chr [1:60520] \"Automatic Import\" \"Automatic Import\" \"Automatic Import\" \"Automatic Import\" ...\n  ..$ id               : chr [1:60520] \"Abbott, Mcbride and Edwards\" \"Abbott-Gomez\" \"Abbott-Harrison\" \"Abbott-Ibarra\" ...\n  ..$ dob              : chr [1:60520] NA NA NA NA ...\n $ links     :'data.frame':\t75817 obs. of  11 variables:\n  ..$ start_date       : chr [1:75817] \"2016-10-29T00:00:00\" \"2035-06-03T00:00:00\" \"2028-11-20T00:00:00\" \"2024-09-04T00:00:00\" ...\n  ..$ type             : chr [1:75817] \"Event.Owns.Shareholdership\" \"Event.Owns.Shareholdership\" \"Event.Owns.Shareholdership\" \"Event.Owns.Shareholdership\" ...\n  ..$ _last_edited_by  : chr [1:75817] \"Pelagia Alethea Mordoch\" \"Niklaus Oberon\" \"Pelagia Alethea Mordoch\" \"Pelagia Alethea Mordoch\" ...\n  ..$ _last_edited_date: chr [1:75817] \"2035-01-01T00:00:00\" \"2035-07-15T00:00:00\" \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" ...\n  ..$ _date_added      : chr [1:75817] \"2035-01-01T00:00:00\" \"2035-07-15T00:00:00\" \"2035-01-01T00:00:00\" \"2035-01-01T00:00:00\" ...\n  ..$ _raw_source      : chr [1:75817] \"Existing Corporate Structure Data\" \"Oceanus Corporations Monthly - Jun '35\" \"Existing Corporate Structure Data\" \"Existing Corporate Structure Data\" ...\n  ..$ _algorithm       : chr [1:75817] \"Automatic Import\" \"Manual Entry\" \"Automatic Import\" \"Automatic Import\" ...\n  ..$ source           : chr [1:75817] \"Avery Inc\" \"Berger-Hayes\" \"Bowers Group\" \"Bowman-Howe\" ...\n  ..$ target           : chr [1:75817] \"Allen, Nichols and Thompson\" \"Jensen, Morris and Downs\" \"Barnett Inc\" \"Bennett Ltd\" ...\n  ..$ key              : int [1:75817] 0 0 0 0 0 0 0 0 0 0 ...\n  ..$ end_date         : chr [1:75817] NA NA NA NA ...\n```\n\n\n:::\n:::\n\n\nIt contains graph data, where nodes can be accessed via `nodes` and edges via `links`. This dataset has a lot of columns but we will only filter the relevant data during wrangling..\n\n# 3 Data Wrangling\n\n## 3.1 Extracting Graph Elements\n\nFor simplicity, we will only extract the columns that are needed to do graph analysis. We will also *ignore* the time elements for now so we will not be including them in the analysis.\n\n::: panel-tabset\n### Nodes\n\nThe nodes represent the entities in the network. They can be people or companies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_nodes_raw <- as_tibble(mc3_data$nodes)\nglimpse(mc3_nodes_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 60,520\nColumns: 15\n$ type                <chr> \"Entity.Organization.Company\", \"Entity.Organizatio…\n$ country             <chr> \"Uziland\", \"Mawalara\", \"Uzifrica\", \"Islavaragon\", …\n$ ProductServices     <chr> \"Unknown\", \"Furniture and home accessories\", \"Food…\n$ PointOfContact      <chr> \"Rebecca Lewis\", \"Michael Lopez\", \"Steven Robertso…\n$ HeadOfOrg           <chr> \"Émilie-Susan Benoit\", \"Honoré Lemoine\", \"Jules La…\n$ founding_date       <chr> \"1954-04-24T00:00:00\", \"2009-06-12T00:00:00\", \"202…\n$ revenue             <dbl> 5994.73, 71766.67, 0.00, 0.00, 4746.67, 46566.67, …\n$ TradeDescription    <chr> \"Unknown\", \"Abbott-Gomez is a leading manufacturer…\n$ `_last_edited_by`   <chr> \"Pelagia Alethea Mordoch\", \"Pelagia Alethea Mordoc…\n$ `_last_edited_date` <chr> \"2035-01-01T00:00:00\", \"2035-01-01T00:00:00\", \"203…\n$ `_date_added`       <chr> \"2035-01-01T00:00:00\", \"2035-01-01T00:00:00\", \"203…\n$ `_raw_source`       <chr> \"Existing Corporate Structure Data\", \"Existing Cor…\n$ `_algorithm`        <chr> \"Automatic Import\", \"Automatic Import\", \"Automatic…\n$ id                  <chr> \"Abbott, Mcbride and Edwards\", \"Abbott-Gomez\", \"Ab…\n$ dob                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n```\n\n\n:::\n:::\n\n\nWe will only retain the following columns:\n\n-   `id` - to serve as the identifier for the node\n\n-   `type` - to differentiate people from companies in the graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_nodes_lite <- mc3_nodes_raw %>% select(id, type)\n```\n:::\n\n\n### Edges\n\nThe edges represent the relationship between different nodes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_edges_raw <- as_tibble(mc3_data$links)\nglimpse(mc3_edges_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 75,817\nColumns: 11\n$ start_date          <chr> \"2016-10-29T00:00:00\", \"2035-06-03T00:00:00\", \"202…\n$ type                <chr> \"Event.Owns.Shareholdership\", \"Event.Owns.Sharehol…\n$ `_last_edited_by`   <chr> \"Pelagia Alethea Mordoch\", \"Niklaus Oberon\", \"Pela…\n$ `_last_edited_date` <chr> \"2035-01-01T00:00:00\", \"2035-07-15T00:00:00\", \"203…\n$ `_date_added`       <chr> \"2035-01-01T00:00:00\", \"2035-07-15T00:00:00\", \"203…\n$ `_raw_source`       <chr> \"Existing Corporate Structure Data\", \"Oceanus Corp…\n$ `_algorithm`        <chr> \"Automatic Import\", \"Manual Entry\", \"Automatic Imp…\n$ source              <chr> \"Avery Inc\", \"Berger-Hayes\", \"Bowers Group\", \"Bowm…\n$ target              <chr> \"Allen, Nichols and Thompson\", \"Jensen, Morris and…\n$ key                 <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ end_date            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n```\n\n\n:::\n:::\n\n\nWe will only retain the following columns:\n\n-   `source` - to identify the *actor* of the relationship, corresponds to `id` in nodes.\n\n-   `target` - to identify the *receiver* of the relationship, corresponds to `id` in nodes.\n\n-   `type` - to identify the type of the relationship\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_edges_lite <- mc3_edges_raw %>% select(source, target, type)\n```\n:::\n\n:::\n\n## 3.2 Closer look at *type*\n\nBoth the `nodes` and `edges` have `type` which contains the type of the nodes and edges. We will assign a `supertype` and a `subtype` from `type`.\n\n::: panel-tabset\n### Nodes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(mc3_nodes_lite$type) %>% unique()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Entity.Organization.Company\"         \n[2] \"Entity.Organization.LogisticsCompany\"\n[3] \"Entity.Organization.FishingCompany\"  \n[4] \"Entity.Organization.FinancialCompany\"\n[5] \"Entity.Organization.NewsCompany\"     \n[6] \"Entity.Organization.NGO\"             \n[7] \"Entity.Person\"                       \n[8] \"Entity.Person.CEO\"                   \n```\n\n\n:::\n:::\n\n\n`supertype` - type of entity, either *Person* or *Organization*\n\n`subtype` - subcategory of *supertype*, e.g., *Company, FishingCompany, CEO*\n\n### Edges\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(mc3_edges_lite$type) %>% unique()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Event.Owns.Shareholdership\"      \"Event.Owns.BeneficialOwnership\" \n[3] \"Event.WorksFor\"                  \"Relationship.FamilyRelationship\"\n```\n\n\n:::\n:::\n\n\n`supertype` - type of relationship, either *Ownership*, *Employment, Relationship.*\n\n`subtype` - subcategory of *supertype*, e.g., *Shareholdership, BeneficialOwnership, FamilyRelationship*\n:::\n\n## 3.3 Preparing the data\n\nWith the considerations above, we will shape the data needed for our graph visualization.\n\n::: panel-tabset\n### Nodes\n\nFor nodes, we will also assign a shape for visualization depending on *supertype.* For people, we will use 📐, while we use 🔴 for organizations.\n\nLastly, we will assign numbers to each node as an alternative label to the ids (as they are long).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPERSON_SHAPE = \"triangle\"\nORGANIZATION_SHAPE = \"circle\"\n\nmc3_nodes_clean <- mc3_nodes_lite %>%\n  mutate(\n    supertype = strsplit(type, \".\", fixed=TRUE) %>% sapply('[', 2),\n    # Get the last type as subtype. In the case of Entity.Person,\n    # both supertype and subtype are \"Person\".\n    subtype = strsplit(type, \".\", fixed=TRUE) %>% sapply(tail, n=1),\n    num = row_number(),\n    shape = ifelse(supertype == \"Person\", PERSON_SHAPE, ORGANIZATION_SHAPE)\n  ) %>%\n  select(id, num, supertype, subtype, shape)\n\nkable(head(mc3_nodes_clean))\n```\n\n::: {.cell-output-display}\n\n\n|id                          | num|supertype    |subtype |shape  |\n|:---------------------------|---:|:------------|:-------|:------|\n|Abbott, Mcbride and Edwards |   1|Organization |Company |circle |\n|Abbott-Gomez                |   2|Organization |Company |circle |\n|Abbott-Harrison             |   3|Organization |Company |circle |\n|Abbott-Ibarra               |   4|Organization |Company |circle |\n|Abbott-Sullivan             |   5|Organization |Company |circle |\n|Acevedo and Sons            |   6|Organization |Company |circle |\n\n\n:::\n:::\n\n\nLet's also check if `supertype`, `subtype`, and `shape` have been mapped correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_nodes_clean %>%\n  group_by(supertype, subtype, shape) %>%\n  summarize(count = n()) %>%\n  arrange(-count) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|supertype    |subtype          |shape    | count|\n|:------------|:----------------|:--------|-----:|\n|Person       |Person           |triangle | 50356|\n|Organization |Company          |circle   |  7927|\n|Person       |CEO              |triangle |  1293|\n|Organization |FishingCompany   |circle   |   600|\n|Organization |LogisticsCompany |circle   |   311|\n|Organization |FinancialCompany |circle   |    23|\n|Organization |NGO              |circle   |     5|\n|Organization |NewsCompany      |circle   |     5|\n\n\n:::\n:::\n\n\n### Edges\n\nFor `ggraph` to plot the edges correctly, we need to assigns weights to the edges. For simplicity, let us assign the number of edges with the same `source`, `target` and `type`.\n\nLastly, we will change `source` and `target` to `from` and `to`, respectively for compatibility with network functions we will use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_edges_clean <- mc3_edges_lite %>%\n  rename(from = source, to = target, ) %>%\n  mutate(\n    supertype = ifelse(\n      grepl(\"Event.Owns\", type),\n      \"Ownership\",\n      ifelse(grepl(\"Relationship\", type), \"Relationship\", \"Employment\")\n    ),\n    subtype = strsplit(type, \".\", fixed = TRUE) %>% sapply(tail, n = 1)\n  ) %>%\n  filter(from != to) %>%\n  group_by(from, to, supertype, subtype) %>%\n  summarize(weight = n())\n\nkable(head(mc3_edges_clean))\n```\n\n::: {.cell-output-display}\n\n\n|from                   |to                                   |supertype  |subtype             | weight|\n|:----------------------|:------------------------------------|:----------|:-------------------|------:|\n|4. SeaCargo Ges.m.b.H. |Dry CreekRybachit Marine A/S         |Ownership  |Shareholdership     |      1|\n|4. SeaCargo Ges.m.b.H. |KambalaSea Freight Inc               |Ownership  |Shareholdership     |      1|\n|9. RiverLine CJSC      |SumacAmerica Transport GmbH & Co. KG |Ownership  |Shareholdership     |      1|\n|Aaron Acosta           |Manning-Pratt                        |Employment |WorksFor            |      1|\n|Aaron Acosta           |Manning-Pratt                        |Ownership  |Shareholdership     |      1|\n|Aaron Allen            |Hicks-Calderon                       |Ownership  |BeneficialOwnership |      1|\n\n\n:::\n:::\n\n\nLastly, let's check if `type` has been mapped correctly to `supertype` and `subtype`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_edges_clean %>%\n  group_by(supertype, subtype) %>%\n  summarize(count = n()) %>%\n  arrange(-count) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|supertype    |subtype             | count|\n|:------------|:-------------------|-----:|\n|Ownership    |Shareholdership     | 39378|\n|Ownership    |BeneficialOwnership | 21529|\n|Employment   |WorksFor            | 14817|\n|Relationship |FamilyRelationship  |    91|\n\n\n:::\n:::\n\n:::\n\n## 3.4 Preparing the supernetwork\n\nWe will prepare the supernetwork from the nodes and edges we prepared.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupernetwork = tbl_graph(edges = mc3_edges_clean,\n                         nodes = mc3_nodes_clean,\n                         directed = TRUE)\n```\n:::\n\n\nWe call this a supernetwork as this is a collection of smaller, unconnected networks.\n\n# 4 Investigating *SouthSeafood Express Corp*\n\nFrom VAST Challenge 2024 [Mini-case 3](https://vast-challenge.github.io/2024/MC3.html):\n\n> Identify the network associated with SouthSeafood Express Corp and visualize how this network and competing businesses change as a result of their illegal fishing behavior. Which companies benefited from SouthSeafood Express Corp legal troubles? Are there other suspicious transactions that may be related to illegal fishing? Provide visual evidence for your conclusions.\n\n::: callout-tip\n## Solving the smaller problem first\n\nAlthough the question about *SouthSeafood Express Corp* is the last question, we will start with investigating its relationships so we can generalize to make inferences to the rest of the network, for Question 3.\n:::\n\nTo do the investigation, our strategy is to start with the smallest network first to the biggest. We will be looking at:\n\n1.  Direct neighbors - They have the strongest influence on and can be influenced the most by *SouthSeafood Express Corp.*\n2.  Sphere of influence - Based on Nicholas A. Christakis and James H. Fowler's theory of [**Three Degrees of Influence**](https://www.strategy-business.com/article/10218), which states that that influence gradually dissipates and eventually cease to be notable beyond the **3rd degree of separation**.\n3.  Full connected network - We will look at the entire network containing the nodes that have paths to *SouthSeafood Express Corp.*\n\nIn order to do this, we need to identify the *SouthSeafood Express Corp* node first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nssfec_node <- which(V(supernetwork)$id == \"SouthSeafood Express Corp\")\n```\n:::\n\n\nWe will use `ego()` and `induced_graph()` functions from `igraph` to generate the subnetworks related to this node.\n\nWe will use the function below to get the subgraphs:\n\n::: {.callout-important collapse=\"true\"}\n## RStudio breaks when defining functions\n\nRstudio breaks as soon as I type `function(){}` in a code chunk.\n\nThis results in not being able to save the file and not being able to run any code chunk. Hence, we will just copy the code below everytime while setting the variables.\n:::\n\n``` r\npar_graph = supernetwork # the graph to extract the subgraph from\npar_nodes = ssfec_node # reference node\npar_distance = 1 # distance from the reference node\n\nfvar_vertices <- ego(par_graph, nodes = par_nodes, order = par_distance)[[1]]\nfvar_igraph_subgraph <- induced_subgraph(par_graph, vids = fvar_vertices)\nfvar_nodes_df <- as_data_frame(fvar_igraph_subgraph, what = \"vertices\") %>% rename(id = name)\nfvar_edges_sf <- as_data_frame(fvar_igraph_subgraph, what = \"edges\")\nout_subgraph <- graph_from_data_frame(fvar_edges_sf, vertices=fvar_nodes_df, directed=TRUE)\n```\n\n## 4.1 Direct Neighbors\n\n### 4.1.1 Extracting the subgraph\n\nWe will first extract the direct neighbors for *SouthSeafood Express Corp.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar_graph = supernetwork\npar_nodes = ssfec_node\npar_distance = 1\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show function code\"}\nfvar_vertices <- ego(par_graph, nodes = par_nodes, order = par_distance)[[1]]\nfvar_igraph_subgraph <- induced_subgraph(par_graph, vids = fvar_vertices)\nfvar_nodes_df <- as_data_frame(fvar_igraph_subgraph, what = \"vertices\")\nfvar_edges_sf <- as_data_frame(fvar_igraph_subgraph, what = \"edges\")\nout_subgraph <- tbl_graph(nodes = fvar_nodes_df, edges=fvar_edges_sf, directed=TRUE)\n```\n:::\n\n\nWe will also add focus on the *SouthSeafood Express Corp* node to emphasize it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nssfec_direct_neighbors <- out_subgraph %>%\n  mutate(focus = (id == \"SouthSeafood Express Corp\"))\n```\n:::\n\n\n### 4.1.2 Plotting the graph\n\nFinally, we can plot the graph of *SouthSeafood Express Corp* direct neighbors.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ggraph code\"}\nggraph(ssfec_direct_neighbors, layout = \"linear\", circular = TRUE) +\n  # Render nodes\n  geom_node_point(aes(color = focus, shape = shape), show.legend = FALSE, size = 30) +\n  geom_node_text(\n    aes(label = str_wrap(id, width = -1)),\n    family = FONT_FAMILY,\n    size = 3,\n    color = \"white\"\n  ) +\n  scale_color_manual(values = c(\"blue\", \"gold3\")) +\n  \n  # Render edges\n  geom_edge_link(\n    aes(label = subtype),\n    # Control arrow\n    arrow = arrow(type = \"closed\", length = unit(0.025, \"npc\")),\n    end_cap = circle(12, \"mm\"),\n    start_cap = circle(12, \"mm\"),\n    # Format labels\n    angle_calc = \"along\",\n    label_dodge = unit(0.04, \"npc\"),\n    family = FONT_FAMILY,\n    show.legend = FALSE\n  ) +\n  \n  # Hack to reduce distance between nodes\n  # This is to not clip the nodes in the edge of the plot\n  # ref: https://stackoverflow.com/a/66991383\n  ylim(-1.3, 0.8) +\n  xlim(-1, 1) +\n  \n  # Style graph\n  unset_graph_style() +\n  theme_graph(base_family = FONT_FAMILY, plot_margin = margin(0)) +\n  plot_annotation(\n    title = \"SouthSeafood Express Corp's Shareholders\",\n    subtitle = \"Two other fishing companies, <span style='color:blue;'>**AguaLeska Transit N.V.**</span> and <span style='color:blue;'>**Tainamarine Fishing Co**</span> hold shares in<br />SouthSeafood Express Corp. They are posed to benefit the most from the company's illegal fishing activities.\") &\n  theme(\n    text = element_text(family = FONT_FAMILY),\n    plot.title = element_text(face = \"bold\", size = rel(1.2)),\n    plot.subtitle = element_markdown(color = \"grey50\", , size = rel(0.9))\n  )\n```\n\n::: {.cell-output-display}\n![](CopyOfTake-home_Ex3_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n::: callout-tip\n#### Insights\n\nAs shareholders, **AguaLeska Transit N.V.** and **Tainamarine Fishing Co** have big influence on where the resources of *SouthSeafood Express Corp* go.\n\nIn this case, most of it will most likely opposite of the arrow direction, i.e. benefitting the shareholders.\n:::\n\n## 4.2 Sphere of influence\n\n### 4.2.1 Extracting the subgraph\n\nWe will first extract the direct neighbors for *SouthSeafood Express Corp.* We will use `distance=3`, based on [**Three Degrees of Influence**](https://www.strategy-business.com/article/10218).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar_graph = supernetwork\npar_nodes = ssfec_node\npar_distance = 3\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show function code\"}\nfvar_vertices <- ego(par_graph, nodes = par_nodes, order = par_distance)[[1]]\nfvar_igraph_subgraph <- induced_subgraph(par_graph, vids = fvar_vertices)\nfvar_nodes_df <- as_data_frame(fvar_igraph_subgraph, what = \"vertices\")\nfvar_edges_sf <- as_data_frame(fvar_igraph_subgraph, what = \"edges\")\nout_subgraph <- tbl_graph(nodes = fvar_nodes_df, edges=fvar_edges_sf, directed=TRUE)\n```\n:::\n\n\nWe will also add focus on the *SouthSeafood Express Corp* node to emphasize it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nssfec_sphere_of_influence <- out_subgraph %>%\n  mutate(focus = (id == \"SouthSeafood Express Corp\"))\n```\n:::\n\n\n### 4.2.2 Plotting the graph\n\nFinally, we can plot the graph of *SouthSeafood Express Corp's* sphere of influence.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ggraph code\"}\nset.seed(911)\nggraph(ssfec_sphere_of_influence, layout = \"nicely\") +\n  geom_node_point(aes(color = focus, shape = shape),\n                  size = 7.5,\n                  show.legend = FALSE) +\n  geom_node_text(\n    aes(label = num),\n    family = FONT_FAMILY,\n    size = 2,\n    color = 'white'\n  ) +\n  geom_edge_link(\n    aes(label = subtype),\n    arrow = arrow(type = \"closed\", length = unit(0.01, \"npc\")),\n    end_cap = circle(4, \"mm\"),\n    start_cap = circle(4, \"mm\"),\n    angle_calc = \"along\",\n    label_dodge = unit(0.02, \"npc\"),\n    label_size = 2,\n    family = FONT_FAMILY\n  ) +\n  scale_color_manual(values = c(\"blue\", \"gold3\")) +\n  scale_alpha_continuous(range = c(1, 0.7)) +\n  \n  # Style graph\n  unset_graph_style() +\n  theme_graph(base_family = FONT_FAMILY, plot_margin = margin(0)) +\n  plot_annotation(title = \"SouthSeafood Express Corp's Sphere of Influence\",\n                  subtitle = \"Entities with 3 degrees of separation from SouthSeafood Express Corp\",\n                  caption = \"*check table below for the names*\") &\n  theme(\n    text = element_text(family = FONT_FAMILY),\n    plot.title = element_text(face = \"bold\", size = rel(1.2)),\n    plot.subtitle = element_markdown(color = \"grey50\", , size = rel(0.9)),\n    plot.caption = element_markdown(color = \"grey50\")\n  )\n```\n\n::: {.cell-output-display}\n![](CopyOfTake-home_Ex3_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nssfec_sphere_of_influence %>% \n  activate(nodes) %>%\n  arrange(num) %>%\n  select(num, id, supertype, subtype) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   num|id                               |supertype    |subtype          |\n|-----:|:--------------------------------|:------------|:----------------|\n| 60429|AguaLeska Transit N.V.           |Organization |FishingCompany   |\n| 60449|Namorna Transit Ltd              |Organization |Company          |\n| 60461|SavanetaCreek Solutions NV       |Organization |LogisticsCompany |\n| 60464|SouthSeafood Express Corp        |Organization |FishingCompany   |\n| 60466|StichtingMarine Shipping Company |Organization |FishingCompany   |\n| 60468|Tainamarine Fishing Co           |Organization |FishingCompany   |\n| 60469|V. Miesel Shipping               |Organization |Company          |\n| 60477|Liam Conti                       |Person       |Person           |\n| 60478|Nadia Conti                      |Person       |Person           |\n| 60479|Fintan Park                      |Person       |Person           |\n| 60481|Sanaa El-Amin                    |Person       |Person           |\n| 60483|Elise Hauser                     |Person       |Person           |\n\n\n:::\n:::\n\n\n::: callout-tip\n#### Insights\n\nThe network map is comprised mostly of *Shareholderships* and *BenificialOwnerships.*\n\n*SouthSeafood Express Corp's (60464)* shareholders, **AguaLeska Transit N.V. (60429)** and **Tainamarine Fishing Co (60468)** have other shareholders.\n\n**StichtingMarine Shipping Company (60466)** holds shares of these companies (through other companies). **SavanetaCreek Solutions NV (60461)**, a Logistics Company holds shareholdership on this Fishing Company as well.\n\nFurthermore, **Liam Conti (60477)** and **Fintan Park (60479)** are the beneficial owners of these companies so they have the final decision-making power. Lastly, as Liam Conti's family member, **Nadia Conti (60478)** may also benefit from Liam's ownership of companies.\n\nThese 5 nodes are candidates to be the most influential nodes in the network and benefit the most from the resources generated by this network.\n:::\n",
    "supporting": [
      "CopyOfTake-home_Ex3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}